var situations = {
        "0": "my internet lost connection",
        "1": "someone talks while muted",
        "2": "can you hear me",
        "3": "someone is too late",
        "4": "accidental noise",
        "5": "how does screen sharing works",
        "6": "roommate walks in",
        "7": "screen freezes",
        "8": "someones cat walks in front of the camera",
        "9": "awkward waving",
        "10": "hear someone typing",
        "11": "someone says vo on bt",
        "12": "julians camera is black and white",
        "13": "guus freezes",
        "14": "the video a company wants to show doesnt work",
        "15": "‘breakout rooms are opened’",
        "16": "someone yawns on camera",
        "17": "‘i am unable to enter the room’",
        "18": "kilian has a question",
        "19": "somebody eats in front of the camera",
        "20": "somebody makes a corona joke",
        "21": "people are sitting together behind their camera",
        "22": "somebody drinks from the adyen water bottle",
        "23": "somebody drinks from the BT coffe cup",
        "24": "Doorbell rings",
        "25": "echo",
        "26": "\"We also organise a kit if activities outside of work\"",
        "27": "Mentions of activities outside of work",
        "28": "skipping break",
        "29": "child on the background",
        "30": "blurred background",
        "31": "image as background",
        "32": "Multiple sony wh1000xm3 headphones",
        "33": "someone says vo on 64",
        "34": "someone left the meeting",
        "35": "Francis has a question",
        "36": "Francis is late",
        "37": "Someone has bingo",
};

module.exports = {
        situations: situations
}
